### ISSUE TITLE
Config Request

### ISSUE THREAD

**Issue by daveminesdiamonds** [ferriarnus/WinterEssentials#1]
Hey man love the mod, just a simple request if I may, would it be at all possible to create a config file for some of the mod features. If not, at least for the snow in any biome feature? I just simply prefer having snow only in snow biomes, not in all,  but love the rest of the features. Thanks a bunch!

**Comment by ferriarnus** [comment]
I will certainly add it in the next update ! Unfortunately I'm just a bit short on time for now.

**Comment by ferriarnus** [comment]
Hmm, the fix seemed easier then I excepted @daveminesdiamonds. I'll update curseforge to have a config option for snow in all biomes and the snow stacking effect. Any other config options you where thinking about?
